### ISSUE TITLE
_config.yml for spanish/english

### ISSUE THREAD

**Issue by jpalanco** [EpicBounties/EpicWeb#10]
This elements are only available on single lang

- title: "EpicBounties"
- description: "La Plataforma De Bug Bounty De Habla Hispana"

**Comment by danisztls** [comment]
They weren't being used in the first place. The old site missed the SEO meta tags. Fixed it.

**Comment by danisztls** [comment]
9d915e6d238f4c6cadb3369c2236b194a2ad318a
