### ISSUE TITLE
Footer is not rendering

### ISSUE THREAD

**Issue by jpalanco** [EpicBounties/EpicWeb#13]
Footer is not rendering

**Comment by danisztls** [comment]
![Screenshot from 2021-06-15 21-36-51](https://user-images.githubusercontent.com/13279154/122140514-d522c380-ce21-11eb-89a2-8bea3a1bec23.png)

This is on my end.

There are bugs related to locomotive scroll. It was problematic prior to the theme refactorization.

- If I click on CTA button on nav it will scroll past the content and show a blank screen.
- Visual glitches while scrolling near the footer.

Can you post a screenshot?
